name: project_2cp_eq11
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  animated_text_kit: ^4.2.2

  flutter:
    sdk: flutter
  lottie: ^2.6.0  


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9  
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  provider: ^6.1.2
  flutter_tts: ^4.2.2
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/backgrounds/
    - assets/icons/profile_pics/
    - assets/icons/
    - assets/icons/trophie_page/
    - assets/audios/
    - assets/images/match/
    - assets/icons/avatars/
    - assets/icons/fennec/
    - assets/icons/games_page/
    - assets/icons/levels_page/
    - assets/icons/login_page/
    - assets/icons/manage_profile_page/
    - assets/icons/settings_page/
    - assets/icons/stats_page/
    - assets/icons/quiz_images/
    - assets/icons/regions_page/
    - assets/icons/quiz_results_page/
    - assets/images/relatedTogames/
    - assets/icons/mini_games_results_page/
    - assets/images/
    - assets/images/choose/
    - assets/images/match_game_page/
    - assets/images/quiz/quiz1/
    - assets/images/quiz/quiz2/
    - assets/images/quiz/quiz3/
    - assets/images/quiz/quiz4/
    - assets/images/quiz/quiz5/
    - assets/images/spot_game_page/
    - assets/images/find_game_page/
    - assets/backgrounds/region1/adventure1/
    - assets/icons/region1/adventure1/
    - assets/backgrounds/region1/adventure2/
    - assets/icons/region1/adventure2/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/fredoka-semi-bold.ttf

    - family: Fredoka2
      fonts:
        - asset: assets/fonts/fredoka-Regular.ttf

    - family: Fredoka3
      fonts:
        - asset: assets/fonts/fredoka-Medium.ttf

    - family: Kavivanar
      fonts:
        - asset: assets/fonts/kavivanar-Regular.ttf

        
