name: project_2cp_eq11
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.6.0  


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9  
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/
    - assets/profile_pics/
    - assets/icons/
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/fredoka-semi-bold.ttf

    - family: Kavivanar
      fonts:
        - asset: assets/fonts/kavivanar-Regular.ttf

        
